import { useState, useEffect, useCallback } from 'react';
import Head from 'next/head';
const PORTFOLIO={rajhi:[{ticker:'1120',name:'الراجحي',shares:10,avgCost:71.86,currency:'SAR'},{ticker:'2222',name:'أرامكو',shares:13,avgCost:27.21,currency:'SAR'},{ticker:'7010',name:'STC',shares:5,avgCost:42.69,currency:'SAR'},{ticker:'9405',name:'ذهب',shares:3,avgCost:26.95,currency:'SAR'}],derayah:[{ticker:'9405',name:'ذهب',shares:14,avgCost:24.34,currency:'SAR'},{ticker:'SPUS',name:'SPUS',shares:3.42,avgCost:53.22,currency:'USD'},{ticker:'SPTE',name:'SPTE',shares:2.0,avgCost:40.47,currency:'USD'},{ticker:'BITB',name:'BITB',shares:3.33,avgCost:38.51,currency:'USD'}]};
const WL_KSA=[{ticker:'4002',name:'مواساة'},{ticker:'1150',name:'الإنماء'},{ticker:'2380',name:'رابغ'},{ticker:'4013',name:'السليمان'},{ticker:'7203',name:'علم'}];
const WL_US=[{ticker:'NVDA',name:'Nvidia'},{ticker:'AAPL',name:'Apple'},{ticker:'TSLA',name:'Tesla'},{ticker:'MSFT',name:'Microsoft'},{ticker:'META',name:'Meta'}];
const USD_SAR=3.75;
function fmt(n,d=2){if(n==null||isNaN(n))return'—';return n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});}
function pct(n){if(n==null||isNaN(n))return'—';return(n>=0?'+':'')+n.toFixed(2)+'%';}
function clr(n){if(n==null||isNaN(n))return'#6B7280';return n>=0?'#10B981':'#EF4444';}
function Row({h,prices}){const p=prices[h.ticker];const pl=p?.price?(p.price-h.avgCost)*h.shares:null;const plp=p?.price?((p.price-h.avgCost)/h.avgCost)*100:null;return(<div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr 1fr',padding:'11px 0',borderBottom:'1px solid #1E293B',alignItems:'center'}}><div><div style={{fontSize:13,fontWeight:700,color:'#38BDF8'}}>{h.ticker}</div><div style={{fontSize:10,color:'#64748B'}}>{h.name} · {h.shares}×</div></div><div style={{textAlign:'right'}}><div style={{fontSize:13,color:'#F1F5F9'}}>{p?.price?fmt(p.price):'...'}</div><div style={{fontSize:11,color:clr(p?.change)}}>{pct(p?.change)}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:11,color:'#94A3B8'}}>avg {fmt(h.avgCost)}</div><div style={{fontSize:10,color:'#64748B'}}>{h.currency}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:13,fontWeight:600,color:clr(pl)}}>{pl!=null?(pl>=0?'+':'')+fmt(pl,0):'...'}</div><div style={{fontSize:11,color:clr(plp)}}>{pct(plp)}</div></div></div>);}
function WRow({item,prices}){const p=prices[item.ticker];const flag=p?.change!=null&&Math.abs(p.change)>=2;return(<div style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 0',borderBottom:'1px solid #1E293B'}}><div style={{display:'flex',alignItems:'center',gap:6}}>{flag&&<span>{p.change>0?'🟢':'🔴'}</span>}<div><span style={{fontSize:12,fontWeight:700,color:'#38BDF8'}}>{item.ticker}</span><span style={{fontSize:11,color:'#64748B',marginLeft:6}}>{item.name}</span></div></div><div style={{textAlign:'right'}}><div style={{fontSize:12,color:'#F1F5F9'}}>{p?.price?fmt(p.price):'...'}</div><div style={{fontSize:11,color:clr(p?.change)}}>{pct(p?.change)}</div></div></div>);}
export default function App(){const[prices,setPrices]=useState({});const[loading,setLoading]=useState(true);const[last,setLast]=useState(null);const[tab,setTab]=useState('portfolio');const[copied,setCopied]=useState(false);const[err,setErr]=useState(null);
const load=useCallback(async()=>{try{setErr(null);const r=await fetch('/api/prices');if(!r.ok)throw new Error();const d=await r.json();setPrices(d.prices||{});setLast(new Date());}catch{setErr('Price fetch failed — retrying in 5 min');}finally{setLoading(false);};},[]);
useEffect(()=>{load();const t=setInterval(load,5*60*1000);return()=>clearInterval(t);},[load]);
const all=[...PORTFOLIO.rajhi.map(h=>({...h,broker:'rajhi'})),...PORTFOLIO.derayah.map(h=>({...h,broker:'derayah'}))];
let costSAR=0,valSAR=0;all.forEach(h=>{const p=prices[h.ticker];const c=h.avgCost*h.shares*(h.currency==='USD'?USD_SAR:1);const v=p?.price?p.price*h.shares*(h.currency==='USD'?USD_SAR:1):c;costSAR+=c;valSAR+=v;});
const totalPL=valSAR-costSAR;const totalPct=(totalPL/costSAR)*100;
const movers=all.map(h=>({...h,change:prices[h.ticker]?.change})).filter(h=>h.change!=null&&Math.abs(h.change)>=2);
const copyForClaude=()=>{const lines=['My Portfolio — Morning Check\n','| Ticker | Name | Shares | Avg | Price | P&L | % |','|---|---|---|---|---|---|---|'];all.forEach(h=>{const p=prices[h.ticker];const pl=p?.price?((p.price-h.avgCost)*h.shares).toFixed(0):'N/A';const plp=p?.price?(((p.price-h.avgCost)/h.avgCost)*100).toFixed(1)+'%':'N/A';lines.push(`| ${h.ticker} | ${h.name} | ${h.shares} | ${h.avgCost} ${h.currency} | ${p?.price??'N/A'} | ${pl} | ${plp} |`);});lines.push(`\nTotal Value: ${fmt(valSAR,0)} SAR`);lines.push(`Total P&L: ${totalPL>=0?'+':''}${fmt(totalPL,0)} SAR (${pct(totalPct)})`);lines.push('\nAnalyze my portfolio and suggest this month DCA plan');navigator.clipboard.writeText(lines.join('\n'));setCopied(true);setTimeout(()=>setCopied(false),2500);};
const card={background:'#0F172A',borderRadius:16,margin:'12px 16px',padding:'16px',border:'1px solid #1E293B'};
const tabBtn=(a)=>({flex:1,padding:'10px 0',border:'none',borderRadius:10,fontSize:13,fontWeight:600,cursor:'pointer',background:a?'#1D4ED8':'transparent',color:a?'#fff':'#64748B'});
return(<><Head><title>محفظتي</title><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="apple-mobile-web-app-capable" content="yes"/><meta name="theme-color" content="#0B1120"/></Head><style>{`*{box-sizing:border-box;margin:0;padding:0}body{background:#0B1120}::-webkit-scrollbar{display:none}`}</style>
<div style={{background:'#0B1120',minHeight:'100vh',color:'#F1F5F9',fontFamily:'-apple-system,sans-serif',maxWidth:430,margin:'0 auto',paddingBottom:80}}>
<div style={{background:'#0F172A',padding:'16px 20px',borderBottom:'1px solid #1E293B',position:'sticky',top:0,zIndex:10}}>
<div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>
<div><div style={{display:'flex',alignItems:'center',gap:8}}><div style={{width:8,height:8,borderRadius:'50%',background:'#10B981',boxShadow:'0 0 6px #10B981'}}/><span style={{fontSize:16,fontWeight:800,color:'#F5A623'}}>محفظتي</span></div><div style={{fontSize:11,color:'#475569',marginTop:2}}>{last?'Updated: '+last.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'}):'Loading...'}</div></div>
<button onClick={load} style={{background:'#1E293B',border:'none',borderRadius:10,padding:'8px 14px',color:'#94A3B8',fontSize:12,cursor:'pointer'}}>{loading?'⟳':'↻ Refresh'}</button></div>
{!loading&&<div style={{marginTop:14,display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,background:'#1E293B',borderRadius:12,padding:'10px 14px'}}>
<div><div style={{fontSize:10,color:'#64748B'}}>Value</div><div style={{fontSize:15,fontWeight:700,color:'#F1F5F9'}}>{fmt(valSAR,0)}</div><div style={{fontSize:9,color:'#64748B'}}>SAR</div></div>
<div><div style={{fontSize:10,color:'#64748B'}}>P&L</div><div style={{fontSize:15,fontWeight:700,color:clr(totalPL)}}>{totalPL>=0?'+':''}{fmt(totalPL,0)}</div><div style={{fontSize:9,color:'#64748B'}}>SAR</div></div>
<div><div style={{fontSize:10,color:'#64748B'}}>Return</div><div style={{fontSize:15,fontWeight:700,color:clr(totalPct)}}>{pct(totalPct)}</div></div></div>}</div>
{err&&<div style={{margin:'12px 16px',padding:'10px',background:'#450A0A',borderRadius:10,fontSize:12,color:'#FCA5A5'}}>{err}</div>}
{movers.length>0&&<div style={{margin:'12px 16px',padding:'12px',background:'#1C1917',borderRadius:12,border:'1px solid #292524'}}><div style={{fontSize:11,color:'#A8A29E',marginBottom:6}}>⚡ Movers +2%</div>{movers.map(m=><div key={m.ticker} style={{display:'flex',justifyContent:'space-between',marginBottom:3}}><span style={{fontSize:12,color:'#38BDF8'}}>{m.ticker} · {m.name}</span><span style={{fontSize:12,fontWeight:700,color:clr(m.change)}}>{pct(m.change)}</span></div>)}</div>}
<div style={{display:'flex',gap:6,margin:'12px 16px',background:'#0F172A',borderRadius:12,padding:4,border:'1px solid #1E293B'}}>
<button style={tabBtn(tab==='portfolio')} onClick={()=>setTab('portfolio')}>📊 Portfolio</button>
<button style={tabBtn(tab==='watch')} onClick={()=>setTab('watch')}>👁 Watchlist</button></div>
{tab==='portfolio'&&<><div style={{margin:'0 16px 6px',fontSize:11,color:'#475569',letterSpacing:'.1em'}}>AL RAJHI CAPITAL</div>
<div style={card}>{PORTFOLIO.rajhi.map((h,i)=><Row key={i} h={h} prices={prices}/>)}</div>
<div style={{margin:'8px 16px 6px',fontSize:11,color:'#475569',letterSpacing:'.1em'}}>DERAYAH GLOBAL</div>
<div style={card}>{PORTFOLIO.derayah.map((h,i)=><Row key={i} h={h} prices={prices}/>)}</div>
<div style={card}><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><span style={{fontSize:12,color:'#F59E0B'}}>⚠️ Gold 9405</span><span style={{fontSize:10,padding:'2px 8px',background:'#F59E0B20',color:'#F59E0B',borderRadius:20}}>Overweight</span></div><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><span style={{fontSize:12,color:'#10B981'}}>✅ STC 7010</span><span style={{fontSize:10,padding:'2px 8px',background:'#10B98120',color:'#10B981',borderRadius:20}}>Next Buy</span></div><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontSize:12,color:'#38BDF8'}}>👁 Mouwasat 4002</span><span style={{fontSize:10,padding:'2px 8px',background:'#38BDF820',color:'#38BDF8',borderRadius:20}}>Watch Q1</span></div></div>
<div style={{margin:'12px 16px'}}><button onClick={copyForClaude} style={{width:'100%',padding:14,background:copied?'#065F46':'#1D4ED8',border:'none',borderRadius:14,color:'#fff',fontSize:15,fontWeight:700,cursor:'pointer'}}>{copied?'✅ Copied — open Claude and paste':'📋 Copy for Claude Analysis'}</button></div></>}
{tab==='watch'&&<><div style={{margin:'0 16px 6px',fontSize:11,color:'#475569',letterSpacing:'.1em'}}>🇸🇦 SAUDI</div>
<div style={card}>{WL_KSA.map((item,i)=><WRow key={i} item={item} prices={prices}/>)}</div>
<div style={{margin:'8px 16px 6px',fontSize:11,color:'#475569',letterSpacing:'.1em'}}>🇺🇸 US</div>
<div style={card}>{WL_US.map((item,i)=><WRow key={i} item={item} prices={prices}/>)}</div>
<div style={{margin:'8px 16px',fontSize:10,color:'#334155',textAlign:'center'}}>🟢/🔴 = moved +2% · Saudi: 15min delay · US: live</div></>}
</div></>);}
